name: build

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: checkout
        uses: actions/checkout@v2

      - name: test
        run:
          make test

      - name: run linters
        run: make run-linters